# Generated by Django 4.1.6 on 2023-03-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('meta_keywords', models.CharField(max_length=300)),
                ('meta_author', models.CharField(max_length=50)),
                ('meta_description', models.CharField(max_length=500)),
            ],
        ),
    ]
