# Generated by Django 4.1.6 on 2023-03-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageconfig',
            name='calling_number',
            field=models.CharField(default=7007013502, max_length=50),
            preserve_default=False,
        ),
    ]
