# Generated by Django 4.1.6 on 2023-03-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_banners'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='button_text',
            field=models.CharField(default='hii', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banners',
            name='caption',
            field=models.CharField(default='hii', max_length=100),
            preserve_default=False,
        ),
    ]
