# Generated by Django 4.1.6 on 2023-03-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_banners_button_text_banners_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='page_name',
            field=models.CharField(default='index', max_length=50),
        ),
    ]
