# Generated by Django 4.1.6 on 2023-03-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_testimonials_alter_banners_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='button_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
